version: 3
images:
  base_image:
    name: registry.access.redhat.com/ubi10/ubi:latest
dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  python:
  - pywinrm
  - aiobotocore>=3.9.0 # Set a higher minimum to avoid excessive backtracking for aws packages
  - boto3==1.43.56 # Pin to avoid excessive backtracking for aws packages
  system:
  - python3-devel [compile] # For compiling ovirt-engine-sdk-python
  galaxy:
    collections:
    - amazon.aws
    - ansible.netcommon
    - ansible.utils
    - awx.awx
    - azure.azcollection
    - cisco.intersight
    - community.aws
    - community.okd
    - community.vmware
    - google.cloud
    - kubernetes.core
    - openstack.cloud
    - ovirt.ovirt
    - theforeman.foreman
  exclude:
    system:
    - qemu-img # from collection ovirt.ovirt - not available in ubi10
